apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-pedidos-e8-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70