apiVersion: v1
kind: Service
metadata:
  name: load-balancer-api-pedidos-e8
  namespace: grupo-08-prod
spec:
  selector:
    app: api-pedidos-e8
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8081
  type: LoadBalancer